### ISSUE TITLE
Cluster/Agent name is missing in grafana 

### ISSUE THREAD

**Issue by jebinjeb** [kube-tarian/kubviz#15]
From grafana unable to filter the events based on cluster name.

Proposal:
Agent sending events to server add cluster/agent name and in grafana add filter for cluster name.

**Comment by ahinvinith** [comment]
Working on it

**Comment by jebinjeb** [comment]
Done as part of https://github.com/kube-tarian/kubviz/commit/4f430a893a236f925d1ecf5f71de9cd1719c8e01
